packages:
  - apps/*
  - packages/*

catalog:
  "@types/react-dom": ^19.2.3
  convex: ^1.33.1
  dotenv: ^17.2.2
  lucide-react: 0.546.0
  next-themes: 0.4.6
  sonner: 2.0.7
  tailwindcss: ^4.1.18
  zod: ^4.1.13
  date-fns: ^4.1.0
