/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ProtectedAdminWithdrawalsRouteImport } from './routes/_protected/admin/withdrawals'
import { Route as ProtectedAdminReconciliationRouteImport } from './routes/_protected/admin/reconciliation'
import { Route as ProtectedAdminKycRouteImport } from './routes/_protected/admin/kyc'
import { Route as ProtectedAdminBankVerificationRouteImport } from './routes/_protected/admin/bank-verification'
import { Route as ProtectedAdminAlertsRouteImport } from './routes/_protected/admin/alerts'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminWithdrawalsRoute =
  ProtectedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminReconciliationRoute =
  ProtectedAdminReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminKycRoute = ProtectedAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminBankVerificationRoute =
  ProtectedAdminBankVerificationRouteImport.update({
    id: '/bank-verification',
    path: '/bank-verification',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminAlertsRoute = ProtectedAdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ProtectedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signout': typeof SignoutRoute
  '/todos': typeof TodosRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/alerts': typeof ProtectedAdminAlertsRoute
  '/admin/bank-verification': typeof ProtectedAdminBankVerificationRoute
  '/admin/kyc': typeof ProtectedAdminKycRoute
  '/admin/reconciliation': typeof ProtectedAdminReconciliationRoute
  '/admin/withdrawals': typeof ProtectedAdminWithdrawalsRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signout': typeof SignoutRoute
  '/todos': typeof TodosRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/alerts': typeof ProtectedAdminAlertsRoute
  '/admin/bank-verification': typeof ProtectedAdminBankVerificationRoute
  '/admin/kyc': typeof ProtectedAdminKycRoute
  '/admin/reconciliation': typeof ProtectedAdminReconciliationRoute
  '/admin/withdrawals': typeof ProtectedAdminWithdrawalsRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signout': typeof SignoutRoute
  '/todos': typeof TodosRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/admin/alerts': typeof ProtectedAdminAlertsRoute
  '/_protected/admin/bank-verification': typeof ProtectedAdminBankVerificationRoute
  '/_protected/admin/kyc': typeof ProtectedAdminKycRoute
  '/_protected/admin/reconciliation': typeof ProtectedAdminReconciliationRoute
  '/_protected/admin/withdrawals': typeof ProtectedAdminWithdrawalsRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signout'
    | '/todos'
    | '/admin'
    | '/dashboard'
    | '/admin/alerts'
    | '/admin/bank-verification'
    | '/admin/kyc'
    | '/admin/reconciliation'
    | '/admin/withdrawals'
    | '/api/auth/callback'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signout'
    | '/todos'
    | '/dashboard'
    | '/admin/alerts'
    | '/admin/bank-verification'
    | '/admin/kyc'
    | '/admin/reconciliation'
    | '/admin/withdrawals'
    | '/api/auth/callback'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signout'
    | '/todos'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/admin/alerts'
    | '/_protected/admin/bank-verification'
    | '/_protected/admin/kyc'
    | '/_protected/admin/reconciliation'
    | '/_protected/admin/withdrawals'
    | '/api/auth/callback'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignoutRoute: typeof SignoutRoute
  TodosRoute: typeof TodosRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/withdrawals': {
      id: '/_protected/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof ProtectedAdminWithdrawalsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/reconciliation': {
      id: '/_protected/admin/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof ProtectedAdminReconciliationRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/kyc': {
      id: '/_protected/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof ProtectedAdminKycRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/bank-verification': {
      id: '/_protected/admin/bank-verification'
      path: '/bank-verification'
      fullPath: '/admin/bank-verification'
      preLoaderRoute: typeof ProtectedAdminBankVerificationRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/alerts': {
      id: '/_protected/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof ProtectedAdminAlertsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminAlertsRoute: typeof ProtectedAdminAlertsRoute
  ProtectedAdminBankVerificationRoute: typeof ProtectedAdminBankVerificationRoute
  ProtectedAdminKycRoute: typeof ProtectedAdminKycRoute
  ProtectedAdminReconciliationRoute: typeof ProtectedAdminReconciliationRoute
  ProtectedAdminWithdrawalsRoute: typeof ProtectedAdminWithdrawalsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminAlertsRoute: ProtectedAdminAlertsRoute,
  ProtectedAdminBankVerificationRoute: ProtectedAdminBankVerificationRoute,
  ProtectedAdminKycRoute: ProtectedAdminKycRoute,
  ProtectedAdminReconciliationRoute: ProtectedAdminReconciliationRoute,
  ProtectedAdminWithdrawalsRoute: ProtectedAdminWithdrawalsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignoutRoute: SignoutRoute,
  TodosRoute: TodosRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
